DROP DATABASE tfi_mascotas;
CREATE DATABASE if NOT EXISTS tfi_mascotas CHARACTER  SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE tfi_mascotas;
-- Clase A
create table mascota (
id BIGINT PRIMARY KEY AUTO_INCREMENT,
eliminado BOOLEAN NOT NULL DEFAULT FALSE,
NOMBRE VARCHAR(60) NOT NULL,
ESPECIE VARCHAR (30) NOT NULL,
RAZA VARCHAR (60),
fechaNacimiento DATE,
DUENIO VARCHAR(120) NOT NULL) ENGINE = InnoDB

;
-- Clase B
CREATE TABLE microchip (
id BIGINT PRIMARY KEY AUTO_INCREMENT,
ELIMINADO BOOLEAN NOT NULL DEFAULT FALSE,
CODIGO VARCHAR(25) NOT NULL,
fechaImplantacion DATE,
VETERINARIA VARCHAR(120),
OBSERVACIONES VARCHAR(255),
mascota_id BIGINT UNIQUE, 
CONSTRAINT uk_microchip_codigo UNIQUE (CODIGO),
CONSTRAINT fk_microchip_mascota FOREIGN KEY (mascota_id) REFERENCES mascota(id) 
ON DELETE CASCADE ) 
ENGINE =InnoDB;
